# Generated by Django 4.1.1 on 2022-09-25 12:12

import applications.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='ref')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('urlLogo', models.URLField(max_length=255, null=True, verbose_name='url_Logo')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('oidAudit', models.BigIntegerField(default=applications.models.sequence_audit_oid, editable=False, verbose_name='oidAudit')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, verbose_name='ref')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname1', models.CharField(max_length=50, null=True, verbose_name='surname1')),
                ('surname2', models.CharField(max_length=50, null=True, verbose_name='surname2')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('password', models.CharField(max_length=256, null=True, verbose_name='password')),
                ('oidAudit', models.BigIntegerField(default=applications.models.sequence_audit_oid, editable=False, verbose_name='oidAudit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='applications.company')),
            ],
        ),
    ]
