# Generated by Django 4.1.1 on 2022-09-25 12:47

import applications.model.genericModel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='ref')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('urlLogo', models.URLField(max_length=255, null=True, verbose_name='url_Logo')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('oidAudit', models.BigIntegerField(default=applications.model.genericModel.getSequenceAuditOid, editable=False, verbose_name='oidAudit')),
            ],
            options={
                'verbose_name': 'Empresas',
                'db_table': 'COMPANY',
            },
        ),
    ]
