# Generated by Django 4.1.1 on 2022-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial')
    ]

    operations = [
        migrations.RunSQL("CREATE SEQUENCE IF NOT EXISTS SEQ_AUDIT_OID INCREMENT 1 START 1 ;")
    ]
