# Generated by Django 4.1.1 on 2022-09-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_company_options_alter_company_urllogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ref',
            field=models.CharField(max_length=50, verbose_name='ref'),
        ),
    ]
