# Generated by Django 4.1.1 on 2022-09-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_client_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='urlLogo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/static'),
        ),
    ]
